### ISSUE TITLE
georss.org is bad

### ISSUE THREAD

**Issue by WraithKenny** [ajturner/geopress#3]
http://georss.org seems to redirect to a attack page. You probably shouldn't link to the domain.

**Comment by WraithKenny** [comment]
Or rather, there's a link, 

This Topic "" Has Been Moved.
New Location is Here.

With a redirect to an attack page.

**Comment by ajturner** [comment]
Thanks - I'll look at it.

(via mobile)

**Comment by ajturner** [comment]
Fixed - thanks. I also turned off new signups and will work to remove the additional spam.
